### ISSUE TITLE
Please, deploy 1.5.0.alpha.10 and 1.5.0.alpha.11 to Maven repo

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctorj-epub3#6]
Release notes:
https://github.com/asciidoctor/asciidoctor-epub3/releases/v1.5.0.alpha.10
https://github.com/asciidoctor/asciidoctor-epub3/releases/v1.5.0.alpha.11

**Comment by slonopotamus** [comment]
@robertpanzer ^

**Comment by robertpanzer** [comment]
I’ve seen the ticket, thanks..
I’ll do the releases as soon as I find the time.

**Comment by robertpanzer** [comment]
Both versions are available on jcenter now.
I triggered the sync to Maven central so that these versions should arrive there too very soon.

**Comment by slonopotamus** [comment]
yay! thanks
